server:
  port: ${SERVER_PORT}
  servlet:
    context-path: /api

spring:
  application:
    name: tech-work-service
  rabbitmq:
    host: ${RABBIT_HOST}
    port: ${RABBIT_PORT}
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}

queue:
  name: techWorkQueue