version: '3'

networks:
  interceptor-service:
    driver: bridge

volumes:
  redis-1-data:
    driver: local
  redis-2-data:
    driver: local
  redis-3-data:
    driver: local
  redis-4-data:
    driver: local
  redis-5-data:
    driver: local
  redis-6-data:
    driver: local

services:
  redis-node-1:
    image: redis:latest
    ports:
      - "7000:7000"
    networks:
      - interceptor-service
    hostname: redis-node-1
    volumes:
      - redis-1-data:/data
      - ./redis:/redis
    command: redis-server /redis/redis.conf --port 7000 --loglevel notice

  redis-node-2:
    image: redis:latest
    ports:
      - "7001:7001"
    networks:
      - interceptor-service
    hostname: redis-node-2
    volumes:
      - redis-2-data:/data
      - ./redis:/redis
    command: redis-server /redis/redis.conf --port 7001 --loglevel notice

  redis-node-3:
    image: redis:latest
    ports:
      - "7002:7002"
    networks:
      - interceptor-service
    hostname: redis-node-3
    volumes:
      - redis-3-data:/data
      - ./redis:/redis
    command: redis-server /redis/redis.conf --port 7002 --loglevel notice

  redis-node-4:
    image: redis:latest
    ports:
      - "7003:7003"
    networks:
      - interceptor-service
    hostname: redis-node-4
    volumes:
      - redis-4-data:/data
      - ./redis:/redis
    command: redis-server /redis/redis.conf --port 7003 --loglevel notice

  redis-node-5:
    image: redis:latest
    ports:
      - "7004:7004"
    networks:
      - interceptor-service
    hostname: redis-node-5
    volumes:
      - redis-5-data:/data
      - ./redis:/redis
    command: redis-server /redis/redis.conf --port 7004 --loglevel notice

  redis-node-6:
    image: redis:latest
    ports:
      - "7005:7005"
    networks:
      - interceptor-service
    hostname: redis-node-6
    volumes:
      - redis-6-data:/data
      - ./redis:/redis
    command: redis-server /redis/redis.conf --port 7005 --loglevel notice

  redis-cluster-creator:
    image: redis:latest
    ports:
      - "6999:6999"
    networks:
      - interceptor-service
    command: redis-cli -p 7000 --cluster create redis-node-1:7000 redis-node-2:7001 redis-node-3:7002 redis-node-4:7003 redis-node-5:7004 redis-node-6:7005 --cluster-replicas 1 --cluster-yes
    depends_on:
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
      - redis-node-5
      - redis-node-6